language: python

sudo: true

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH
        - CXX="g++-8"
        - CC="gcc-8"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8
            - ninja-build

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.data

install:
    - pip install -U pip
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
          pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp27-cp27mu-linux_x86_64.whl;
      else
          pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl;
      fi
    - pip freeze

branches:
    only:
        - master

jobs:
    fast_finish: true
    include:
        - stage: 2.7 test 1
          python: 2.7
          script:
              - cat /proc/cpuinfo
              - OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python conv2d.py
              - python conv2d.py
        - stage: 2.7 test 2
          python: 2.7
          script:
              - cat /proc/cpuinfo
              - OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python conv2d.py
              - python conv2d.py
        - stage: 3.6 test 1
          python: 3.6
          script:
              - cat /proc/cpuinfo
              - OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python conv2d.py
              - python conv2d.py
        - stage: 3.6 test 2
          python: 3.6
          script:
              - cat /proc/cpuinfo
              - OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python conv2d.py
              - python conv2d.py
